FROM gcc:latest
WORKDIR /app
COPY T4P2.c .
RUN apt-get update && apt-get install -y \
    libzmq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN gcc T4P2.c -o T4P2 -lzmq
CMD ["./T4P2"]
